export const SAMPLE_MD = [
  '# Como Integrar',
  '',
  'As APIs de Integração é um serviço fornecido pela Tray.',
  '',
  '## Ambiente de Teste',
  '',
  'Não possuímos um ambiente específico para teste.',
  '',
  '## Autorizando seu Aplicativo',
  '',
  'A autenticação via OAuth 2.0 é necessária.',
  '',
  '### Fluxo de autorização',
  '',
  '1. Redirecionar para auth.php',
  '2. Receber código',
  '',
  '# Autorização',
  '',
  'API de autorização.',
  '',
  '## Gerar Chaves de Acesso',
  '',
  '```shell',
  'curl -X POST "https://api.tray.com.br/auth"',
  '```',
  '',
  '```php',
  '<?php',
  '$response = file_get_contents("...");',
  '```',
  '',
  '# API de Produtos',
  '',
  '## POST /products',
  '',
  'Cria produto novo.',
  '',
  '### Campos obrigatórios',
  '',
  '- name',
  '- price',
].join('\n');

/** Plano citava 8; há 9 headings no SAMPLE_MD. */
export const EXPECTED_SECTIONS_COUNT = 9;
